# Permalinks
permalink:        pretty

# Server
dest:             ./_gh_pages
root:             ./

# Custom vars
version:          <%= pkg.version %>
repo:             https://github.com/assemble/boilerplate-swig

download_source:  https://github.com/assemble/boilerplate-swig/archive/v0.2.0.zip

cdn_css:          //netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css
cdn_js:           //netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js
